# Ruff configuration
[tool.ruff]
exclude = [
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "dist",
]
fixable = ["ALL"]
line-length = 100

  [tool.ruff.lint]
  select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
  ]

  [tool.ruff.format]
  quote-style = "double"

#Mypy configuration
[tool.mypy]
exclude = ['(^|/)test/.*']
explicit_package_bases = true
strict_optional = false
