FROM python:3.12

RUN pip install poetry==2.*

WORKDIR /orchestrator
#ENV PYTHONPATH=/code

COPY ./applications/orchestrator/pyproject.toml /orchestrator/pyproject.toml
COPY ./applications/orchestrator/poetry.lock /orchestrator/poetry.lock
COPY ./applications/packages/contracts/ /packages/contracts/

RUN poetry install

COPY ./applications/orchestrator/ /orchestrator/

CMD ["poetry", "run", "python", "-m", "fastapi", "run", "orchestrator/main.py", "--port", "80", "--reload"]
